version: "3.8"

services:
  docker_con:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_con
    depends_on:
      - postgres_con
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres_con:
    image: 'postgres:14'
    container_name: postgres_con
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb